id: automate_mail_fetch
namespace: rejectedly_yours

variables:
  script_path: "scriptsscript.py"
  python_image: "python:3.9-slim"

tasks:
  - id: run_script
    type: io.kestra.plugin.scripts.python.Python
    docker:
      image: {{ vars.python_image }}
    script: |
      python {{ vars.script_path }}

triggers:
  - id: hourly_trigger
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 * * * *"